# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elementy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('koprus', models.IntegerField(default=0)),
                ('pinaka', models.IntegerField(default=0)),
                ('tkanina', models.IntegerField(default=0)),
                ('struktura', models.IntegerField(default=0)),
                ('tkaninySAP', models.IntegerField(default=0)),
                ('czas', models.IntegerField(default=0)),
                ('dominik', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SAPImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.IntegerField()),
                ('name', models.TextField()),
                ('scheduledDate', models.DateField()),
                ('createDate', models.DateField()),
                ('createTime', models.TimeField()),
                ('ackDate', models.DateField()),
                ('ackTime', models.TimeField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementy.Elementy')),
            ],
        ),
        migrations.AddField(
            model_name='access',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementy.Elementy'),
        ),
    ]
